index:
  path: /
  controller: App\Controller\DefaultController::index

index_catch_all:
  path: /{req}
  controller: App\Controller\DefaultController::index
  requirements:
    req: ".+"

some_route:
  path: /some-path