health_check:
  path: /healthz
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: static/health.html.twig

index:
  path: /
  controller: App\Controller\DefaultController::index

index_wilcard:
  path: /{anything}
  controller: App\Controller\DefaultController::index
  defaults:
    anything: ~
  requirements:
    anything: ".+"

some_route:
  path: /some-path
